# ==============================================================
# The document descripts deployment parameters that defines 
# which file is fundamental and how to install these necessary 
# components. 
#
# @author: Xiaoyang Sun (xshaun@outlook.com). 
# Welcome e-mails from consulting and communicating.
# --------------------------------------------------------------


# ==============================================================
# The following descripts parameters' definations and values.
# Users can customize each field as their own demands. 

# [$]
# It defines the mode of deploying hadoop cluster. 
# Optional values as following:
#   - standalone
#   - pseudo-distributed 
#   - fully-distributed
#
mode: 'pseudo-distributed' 

# [$]
# It defines the folder's absolute path of source code or binary. 
# Empty or non-existing folder is fine bacasuse the stage of 
# 'clear' and 'download' can create it automatically.
# !!! Must ensure its correctness and avoid misoperations.!!!
#
codefolder: '/opt/rose-source-on-hadoop/'

# [$]
# Here descripts host, username and password of overall roles 
# including deamons in Yarn and HDFS and also a proxy that helps
# manage the cluster. 
#
# Abbreviation: 
#   controlp - control proxy (controller)
#   resourcem - reource manager (in Yarn)
#   nodem - node manager (in Yarn)
#   datan - data node (in HDFS)
#   namen - name node (in HDFS)
#
roles:
  'controlp': 
    'host': 'localhost'
    'usr': 'boy'
    'pwd': 'xboy'

  'resourcem':
    'hosts':
      - 'localhost' # primary
    'usr': 'boy'
    'pwd': 'xboy'

  'nodem':
    'hosts':
      - 'localhost'
    'usr': 'boy'
    'pwd': 'xboy'

  'datan':
    'hosts':
      - 'localhost' # primary 
      - 'localhost' # secondary
    'usr': 'boy'
    'pwd': 'xboy'

  'namen':
    'hosts':
      - 'localhost'
    'usr': 'boy'
    'pwd': 'xboy'

# [$]
# Here defines concrete content/script(s) in each step that is
# minimum unit of scheduling.
# 
# Make 'scripts/' as root directory and define value format is 
# 'roles.function', such as 'controlp.clear_codefolder'. The 
# point(.) means folder separator so users can customize 
# hierarchical structure to organize customized scripts, such as
# 'fruit.banana.eaten' means './scripts/fruit/banana/eaten.py'
#
steps:
  # install prerequisites used to compile hadoop
  'cpicp': 'controlp.install_compilation_prerequisites'
  # remove all files under codepath folder
  'cpcc': 'controlp.clear_codefolder'
  # download binary code into codefolder
  'cpdbc': 'controlp.download_bin_code'
  # download source code into codefolder
  'cpdsc': 'controlp.download_src_code'
  # compile source code under codepath folder
  'cpcsc': 'controlp.compile_src_code'
  # distribute binary package to nodes
  'cpdbp': 'controlp.distribute_binary_package'

  # prerequisites while running hadoop
  'cirp': 'common.install_runtime_prerequisites'
  
# [$]
# Here defines concrete steps in each stage that is combination 
# of several processes/steps.
#
stages:
  'all' : 
    - 'cpicp'
    - 'cpcc'
    - 'cpdsc'
    - 'cpcsc'

  'clear':
    - 'cpcc'

  'test' : 
    - 'cpdbc'
