# 

mode: 'pseudo_dis' # ['pseudo_dis' | 'fully_dis']

codepath: '/opt/rose-on-hadoop-dev/' # absolute path 

#
# ag: admin gateway.
# rm: reource manager
# nm: node manager
#
roles:
  'ag': 
    'host': 'localhost' #  must
    'pwd': 'xboy'

  'rm':
    'hosts':
      - 'localhost' # first hostname
      - 'localhost' # second hostname
    'pwd': 'xboy'

  'nm':
    'hosts':
      - 'localhost' 
      - 'localhost'
    'pwd': 'xboy'

#
# Naming Rules: R.?.F
#   R -> one role, the script runs in R.
#   ? -> custom notes.
#   F -> (must be)function name. 
#
timelines:
  - 'ag.compile_prerequisites'    # install prerequisites used to compile hadoop
  - 'ag.clear_codepath'           # remove all files under codepath folder
  # - 'ag.download_bin_code'        # download binary code into codepath
  - 'ag.download_src_code'        # download source code into codepath
  - 'ag.compile_src_code'         # compile source code under codepath folder
  
#  - 'pre_runtime_env'      # prerequisites while running hadoop
#  - 'deployment'           # deploy all roles
#  - 'startup'              # start hadoop
#  - 'launch_examples'      # run some examples for testing
#  - 'shutdown'             # stop hadoop
