# 

---
mode: 'pseudo_dis' # ['pseudo_dis' | 'fully_dis']

codepath: '/rose_on_hadoop/'

roles:
  'ag': 'localhost' # admin gateway

  'rm': # reource manager
    - 'host1' # first hostname
    - 'host2' # second hostname

  'nms': # node managers
    - 'nm1' 
    - 'nm2'

timelines:
  - 'pre_compile_env'      # prerequisites while compiling hadoop
  - 'pre_runtime_env'      # prerequisites while running hadoop
  - 'code_clean_folder'    # remove all files under codepath folder
  - 'code_download_bin'    # download binary code into codepath
  - 'code_download_src'    # download source code into codepath
  - 'code_clean_bin'       # mvn clean compiled temporary files
  - 'code_compile'         # compile source code under codepath
  - 'deployment'           # deploy all roles
  - 'startup'              # start hadoop
  - 'launch_examples'      # run some examples for testing
  - 'shutdown'             # stop hadoop
