# 

mode: 'pseudo_dis' # ['pseudo_dis' | 'fully_dis']

codepath: '/opt/rose-source-on-hadoop/' # absolute path 

#
# ag: admin gateway
# rm: reource manager (in yarn)
# nm: node manager (in yarn)
# dn: data node (in hdfs)
# nn: name node (in hdfs)
#
# ---
# For example: under pseudo_dis mode
#
# roles:
#   'ag': 
#     'host': 'localhost'
#     'pwd': 'xboy'
#   'rm':
#     'hosts':
#       - 'localhost'
#     'pwd': 'xboy'
#   'nm':
#     'hosts':
#       - 'localhost'
#     'pwd': 'xboy'
# ---
#
roles:
  'ag': 
    'host': 'localhost' #  must
    'pwd': 'xboy'

  'rm':
    'hosts':
      - 'localhost' # primary
    'usr': 'boy'
    'pwd': 'xboy'

  'nm':
    'hosts':
      - 'localhost'
    'usr': 'boy'
    'pwd': 'xboy'

  'dn':
    'hosts':
      - 'localhost' # primary 
      - 'localhost' # secondary
    'usr': 'boy'
    'pwd': 'xboy'

  'nn':
    'hosts':
      - 'localhost'
    'usr': 'boy'
    'pwd': 'xboy'


#
# Naming Rules: R.?.F
#   R -> one role, the script runs in R.
#   ? -> custom notes.
#   F -> (must be)function name. 
#
timelines:
  - 'ag.install_compilation_prerequisites'    # install prerequisites used to compile hadoop
  - 'ag.clear_codepath'                       # remove all files under codepath folder
  - 'ag.download_bin_code'                    # download binary code into codepath
  - 'ag.download_src_code'                    # download source code into codepath
  - 'ag.compile_src_code'                     # compile source code under codepath folder
  
  # - 'com.install_runtime_prerequisites'       # prerequisites while running hadoop
  # - 'rm.configure_daemon'                     # configuration
  # - 'nm.configure_daemon'                     # configuration
  # - 'com.distribute_binary'                   # deployment 

  # - 'com.start_rose'                          # start rose
  # - 'am.test_usability'                       # run samples
  # - 'com.stop_rose'                           # stop rose
